### ISSUE TITLE
Installation failure with Python 3.10

### ISSUE THREAD

**Issue by jpiggod** [haessar/peaks2utr#1]
Installation of `peaks2utr` within a conda virtual environment with Python 3.10 seems to fail:

```
# Create a new virtual environment using conda
conda create --name peaks2utr

# Activate the newly created virtual environment
conda activate peaks2utr
conda install pip
```

This should have installed the default Python version. I went to check which python version by 
```
python3 --version
```
which turns out to be
```
Python 3.10.8
```

Version of pip(pip3) is
```
pip 22.3.1 from ~/opt/miniconda3/envs/peaks2utr/lib/python3.10/site-packages/pip (python 3.10)
```
(where I manually replaced my home directory with `~`)

Then I installed `peaks2utr` by typing
```
pip install peaks2utr
```

I got the following error messages:
```
Collecting peaks2utr
  Using cached peaks2utr-0.2-py3-none-any.whl (14 kB)
Collecting pysam
  Downloading pysam-0.20.0-cp310-cp310-macosx_10_9_x86_64.whl (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 9.4 MB/s eta 0:00:00
Collecting MACS2
  Using cached MACS2-2.2.7.1.tar.gz (2.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      CRITICAL: Python version must >= 3.6!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

The error message looks weird because I was indeed using Python>=3.6.
I also tried to install from source, but the same error message (from `MACS2`) persisted.
(Just a minor issue but the package `build` also needs to be installed in the newly created virtual environment for the "install from source" method).

Somehow, then I tried to create another virtual environment specifying the Python version to be used, and it finally worked this time (i.e., the installation was successful).
I specified Python 3.8 this time, as suggested by the manuscript uploaded to bioRxiv.
```
conda create --name peaks2utr_v2 python=3.8
conda activate peaks2utr_v2
```

Python version is:
```
Python 3.8.15
```

**Comment by haessar** [comment]
Thanks for flagging this up. I'm also seeing the same issue with python 3.11.0. Will investigate.

**Comment by haessar** [comment]
The MACS2 error has been cleared up with release of https://github.com/haessar/peaks2utr/releases/tag/v0.4 (update to MACS3). However, there is still an installation issue with python versions > 3.9 which I'll attempt to fix (see traceback)

`Traceback (most recent call last):
  File "/home/haessar/build_peaks2utr/peaks2utr/venv/bin/peaks2utr", line 8, in <module>
    sys.exit(main())
  File "/home/haessar/build_peaks2utr/peaks2utr/venv/lib/python3.10/site-packages/peaks2utr/__init__.py", line 50, in main
    limit_memory(constants.PERC_ALLOCATED_VRAM * psutil.virtual_memory().total / 100)
  File "/home/haessar/build_peaks2utr/peaks2utr/venv/lib/python3.10/site-packages/peaks2utr/utils.py", line 99, in limit_memory
    resource.setrlimit(resource.RLIMIT_AS, (maxsize, hard))
TypeError: 'float' object cannot be interpreted as an integer
`

**Comment by saxovocal** [comment]
It seems like Python 3.7.12 also has the same problem, as it redirects to MACS2. Probably a good idea to set pre-requisite as Python 3.8-3.9? Python 3.8 definitely works though, thanks @jpiggod 

```
Collecting peaks2utr
  Using cached peaks2utr-0.2-py3-none-any.whl (14 kB)
Collecting requests (from peaks2utr)
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting gffutils==0.10.1 (from peaks2utr)
  Using cached gffutils-0.10.1.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... done
Collecting pysam (from peaks2utr)
  Using cached pysam-0.21.0.tar.gz (4.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting MACS2 (from peaks2utr)
  Using cached MACS2-2.2.7.1.tar.gz (2.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [4 lines of output]
  Requirement already satisfied: numpy>=1.17 in /tmp/pip-build-env-1rtab9bf/overlay/lib/python3.7/site-packages (1.21.6)
  error in MACS2 setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after name and no valid version specifier)
      numpy>=>=1.17
           ^
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.
```

**Comment by haessar** [comment]
Thanks for notifying me @saxovocal. I do indeed have pre-requisites for py3.8-3.10, but this didn't apply to some older versions of peaks2utr on PyPI (0.1 and 0.2), which I've now yanked. Users using py3.7 will now be met with a python version error when trying to pip install.
