### ISSUE TITLE
Questions about three_prime_utr annotation behavior 

### ISSUE THREAD

**Issue by JHCCoder** [haessar/peaks2utr#15]
Hi Haessar, 

Thanks for the awesome tool. 
Here is a quick question with regards to an unexpected behavior of peaks2utr run where everything was on default setting except the --max-distance which I have set to 1500. I've shared two IGV screenshot below, where you can see the bam file I've used as input, and two gtf tracks, the top one is used as input, and the bottom one is the peaks2utr output where three_prime_utr has been added. 

For the LOC111094256, although the alignment depth was not very deep, just 10 or so the tool added a three prime UTR. 
<img width="1272" alt="Screen Shot 2023-04-26 at 7 05 30 PM" src="https://user-images.githubusercontent.com/47759962/234742607-52a6dbba-a01d-490e-b0ea-b04353b1764e.png">

However, for GAD1, even though the alignment depth was much deeper (~200), the tool did not add a three prime UTR like I would expect. 
<img width="1318" alt="Screen Shot 2023-04-26 at 7 04 22 PM" src="https://user-images.githubusercontent.com/47759962/234742828-f08b50a7-7f73-4af1-b9c0-c43da89b2fbc.png">

Why is this? What parameter could I tweak so that I can get these obvious three prime UTRs in my new gene annotations? Thank you! I am using 0.5.1. 

Best,
JC

**Comment by haessar** [comment]
This is an interesting case. If you run with --keep-cache and open the .cache/forward_peaks.broadPeak file, can you see any in the approximate range 15,403,800 - 15,404,700? If not, that means MACS has failed to call a broad peak in a region with very clear read coverage. This would be cause for concern as the broad peaks are used as the starting points to determine regions of interest for peaks2utr.
