### ISSUE TITLE
ValueError: Duplicate ID 

### ISSUE THREAD

**Issue by JHCCoder** [haessar/peaks2utr#18]
Hi Haessa, 

I am using peak2utr 1.0.0 with gffutils 0.10.1, this is the error I get when I run it on my gff file. Is this an issue with the format of my gff or bam file? (I've attached my full error log as well)

  File "/home/jhc103/miniconda3/envs/toolshed-peaks2utr-latest/lib/python3.9/site-packages/gffutils/create.py", line 507, in create
    self._populate_from_lines(self.iterator)
  File "/home/jhc103/miniconda3/envs/toolshed-peaks2utr-latest/lib/python3.9/site-packages/gffutils/create.py", line 591, in _populate_from_lines
    fixed, final_strategy = self._do_merge(f, self.merge_strategy)
  File "/home/jhc103/miniconda3/envs/toolshed-peaks2utr-latest/lib/python3.9/site-packages/gffutils/create.py", line 226, in _do_merge
    raise ValueError("Duplicate ID {0.id}".format(f))
ValueError: Duplicate ID cds-XP_003638833.2

Thanks! 

[error_log.txt](https://github.com/haessar/peaks2utr/files/11446679/error_log.txt)

**Comment by JHCCoder** [comment]
Hi @haessar, 
The gff is from refseq (https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/002/285/GCF_000002285.5_Dog10K_Boxer_Tasha/) with the wget link [here](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/002/285/GCF_000002285.5_Dog10K_Boxer_Tasha/GCF_000002285.5_Dog10K_Boxer_Tasha_genomic.gff.gz). 

Here is the output with the gff. Is this gff format problematic? 

NC_006583.4	Gnomon	CDS	1317509	1317592	.	-	0	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1285357	1285429	.	-	0	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1283470	1283586	.	-	2	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1282525	1282650	.	-	2	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1281587	1281647	.	-	2	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1279545	1279642	.	-	1	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1277567	1277646	.	-	2	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1276443	1276562	.	-	0	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1275268	1275377	.	-	0	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1274301	1274366	.	-	1	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1273918	1273990	.	-	1	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1271589	1271697	.	-	0	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1269237	1269368	.	-	2	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1267437	1267468	.	-	2	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1266156	1266283	.	-	0	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1264736	1264805	.	-	1	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1263921	1264008	.	-	0	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1262129	1262298	.	-	2	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1261248	1261299	.	-	0	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1259193	1259347	.	-	2	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1257503	1257632	.	-	0	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1252828	1252908	.	-	2	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1251863	1251995	.	-	2	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1250132	1250294	.	-	1	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2
NC_006583.4	Gnomon	CDS	1248058	1248228	.	-	0	ID=cds-XP_003638833.2;Parent=rna-XM_003638785.4;Dbxref=GeneID:100856150,Genbank:XP_003638833.2,VGNC:VGNC:40374;Name=XP_003638833.2;gbkey=CDS;gene=ENPP1;product=ectonucleotide pyrophosphatase/phosphodiesterase family member 1;protein_id=XP_003638833.2

**Comment by JHCCoder** [comment]
Hi @haessar , 

The gff file itself is too large to attach.

**Comment by haessar** [comment]
Hi @JHCCoder, sorry about the delay. This refseq gff will not work because there are duplicate features (i.e. features that have identical ID and Parent attributes) which goes against the expected GFF3 spec (see https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md and discussion [here](https://github.com/daler/gffutils/issues/8#issuecomment-14192875). You will need to use an alternative gff input without this duplication, or manually remove duplicated features before using it with peaks2utr.

**Comment by JHCCoder** [comment]
Hi @haessar, 

I am still somewhat confused because the lines that are sharing the same ID are CDSs which should be considered discontinuous features. And according to the gff3 specification @ https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md 
> In the case of discontinuous features (i.e. a single feature that exists over multiple genomic locations) the same ID may appear on multiple lines. All lines that share an ID must collectively represent a single feature.

I've checked human genome annotation as well, the IDs of CDS for each gene also share the same IDs. I've added merge_strategy="create_unique" to the gffuntils's create_db function in the preprocessing.py file and it allowed peaks2utr to run on this gff3 file. Do you think this is appropriate?

**Comment by haessar** [comment]
This is a good find which I hadn't considered. I will implement this in the next release.
