### ISSUE TITLE
Error in trying to run Demo

### ISSUE THREAD

**Issue by oneito** [haessar/peaks2utr#20]
Hello,

I was able to successfully install peaks2utr but I tried to execute demo I got this error:
TypeError: cannot pickle '_io.TextIOWrapper' object

How can this be solved?

Thanks.

**Comment by haessar** [comment]
Hi @oneito, are you using macOS by any chance?

**Comment by oneito** [comment]
Yes, I am using macOS, The BigSur.

**Comment by oneito** [comment]
Alright, let me try this and see. Thank you.

What do you think about using bulk RNA-seq instead of single cell?
