### ISSUE TITLE
What is the default for the option '--max-distance'?

### ISSUE THREAD

**Issue by Squalomix** [haessar/peaks2utr#23]
I wonder what the default for the option '--max-distance' is. We could not find any information about this in the command's help, publication, and documentation on GitHub. I would really appreciate your response.

**Comment by haessar** [comment]
Thanks for flagging this up. Default value is 200. I will make sure to document this in the help text (along with other defaults)

**Comment by haessar** [comment]
default values now documented in help text with release v1.2.0

**Comment by Squalomix** [comment]
Thank you very much for your response. We are using peaks2utr for vertebrates, so we'll be trying out larger values for that option.
