### ISSUE TITLE
OSError: [Errno 39] Directory not empty: '/path/to/.cache'

### ISSUE THREAD

**Issue by AnnaAMonaco** [haessar/peaks2utr#24]
Hi,

First of all thanks for this tool, I work with many non-traditional model animals and this has been great for improving the in-house gene annotations we have for them. `peaks2utr` has worked for me on 3 different species, but now I keep running into the same error with one specific species (ateAlb), and I don't understand what the issue is.

I have been running `peaks2utr` as follows:
```
> peaks2utr --extend-utr -p 10 -o $outGtf --gtf $inGtf $inBam
#inBam = a merge of 10X scRNAseq bam files from ateAlb
#inGtf = in house annotation in gff3 format

> head $inGtf
ateAlb2.1       funannotate     transcript      76692   86162   .       -       .       transcript_id "Aalb_00004274-T1"; gene_id "Aalb_00004274"
ateAlb2.1       funannotate     exon    76692   79108   .       -       .       transcript_id "Aalb_00004274-T1"; gene_id "Aalb_00004274";
ateAlb2.1       funannotate     exon    82165   82457   .       -       .       transcript_id "Aalb_00004274-T1"; gene_id "Aalb_00004274";
ateAlb2.1       funannotate     exon    84823   85591   .       -       .       transcript_id "Aalb_00004274-T1"; gene_id "Aalb_00004274";
ateAlb2.1       funannotate     exon    85672   85898   .       -       .       transcript_id "Aalb_00004274-T1"; gene_id "Aalb_00004274";
ateAlb2.1       funannotate     exon    85993   86162   .       -       .       transcript_id "Aalb_00004274-T1"; gene_id "Aalb_00004274";
ateAlb2.1       funannotate     transcript      153660  157786  .       +       .       transcript_id "Aalb_00004275-T1"; gene_id "Aalb_00004275"
ateAlb2.1       funannotate     exon    153660  155351  .       +       .       transcript_id "Aalb_00004275-T1"; gene_id "Aalb_00004275";
ateAlb2.1       funannotate     exon    155474  156732  .       +       .       transcript_id "Aalb_00004275-T1"; gene_id "Aalb_00004275";
ateAlb2.1       funannotate     exon    156956  156983  .       +       .       transcript_id "Aalb_00004275-T1"; gene_id "Aalb_00004275";
```

I attached is the full terminal output for the `peaks2utr` run with the whole traceback for the errors, but these are the two main error messages I get:
```
  File "/home/.local/lib/python3.10/site-packages/gffutils/bins.py", line 79, in bins
    if start >= MAX_CHROM_SIZE or stop >= MAX_CHROM_SIZE:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```
and
```
  File "/pkg/python-3.10.10-1/lib/python3.10/shutil.py", line 729, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/path/to/.cache'
```

Could you help solve this issue? I don't even now where to begin with as the cache should be cleared (it does state `2023-11-03 20:54:57,929 - INFO - Clearing cache.` in the log), nor do I understand where the `NoneType` is coming from. I'm using `peaks2utr 1.1.0`.

Thank you in advance,
Anna

[peaks2utr_log.txt](https://github.com/haessar/peaks2utr/files/13295501/peaks2utr_log.txt)

## EDIT TO ADD:
```
> ls ./.cache
forward_peaks.broadPeak   forward_peaks.xls        reverse_peaks.gappedPeak
forward_peaks.gappedPeak  reverse_peaks.broadPeak  reverse_peaks.xls
```

**Comment by haessar** [comment]
Hi Anna, thanks for using peaks2utr and sorry you've encountered this. It looks from the full like traceback that it's being caused by gffutils when trying to create a feature database from the input gtf file. I've tried calling gffutils.create_db on a gtf file composed of the head of your $inGtf (posted above) and it runs without issue, which leads me to suspect there might potentially be a formatting issue elsewhere in $inGtf.
If you are happy to share the full file (either as attachment here or via email if you prefer) I'm happy to have a look. If not, you could try running peaks2utr again with a smaller subset of $inGtf to see if you still encounter an issue (just to diagnose if there is indeed an issue in the file format).

**Comment by AnnaAMonaco** [comment]
Thank you @haessar ! I now checked and did notice something weird in the gff header. I fixed it and I'm running `peaks2utr` again. If it still doesn't work I'm happy to share the gff file troubleshooting :)

Cheers,
Anna

**Comment by AnnaAMonaco** [comment]
Hi @haessar, I tried on the first 500 lines of the gtf and got the same error. Could I get a contact for a safe transfer of the gtf for troubleshooting? 

Cheers,
Anna

**Comment by haessar** [comment]
Hi Anna,
As it's just 500 lines, you could send it to my email: william.haese-hill@glasgow.ac.uk, if you like.
Best,
Will

**Comment by haessar** [comment]
I've stepped through the code and it looks like GFFUtils has an issue with two overlapping transcripts when parsing the GTF file. The following (highlighted in red) is the first example that triggers the error:
![image](https://github.com/haessar/peaks2utr/assets/11962461/775abc5e-82ff-460e-8c31-9973f7590db4)
Do you know if this is an intended feature of the GTF file (e.g. alternative splicing)? If so, I know that I can call gffutils.create_db with disable_infer_genes=True and it prevents the error from occurring. However, I'd have to check whether this would have a knock-on effect downstream (I believe peaks2utr will complain about the lack of "gene" features).

**Comment by haessar** [comment]
I think this might have cleared itself up with the latest release of gffutils (0.12), which I've incorporated into peaks2utr >= v1.2.1. Please feel free to try again with this latest version, and sorry it's taken a couple of months since last response.

**Comment by AnnaAMonaco** [comment]
Late update to confirm that this fixed itself with the newer version of peaks2utr :) Thank you again!
